// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file hk_image.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_HK_IMAGE_H_
#define _FAST_DDS_GENERATED_HK_IMAGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HK_IMAGE_SOURCE)
#define HK_IMAGE_DllAPI __declspec( dllexport )
#else
#define HK_IMAGE_DllAPI __declspec( dllimport )
#endif // HK_IMAGE_SOURCE
#else
#define HK_IMAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HK_IMAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure hk_image defined by the user in the IDL file.
 * @ingroup hk_image
 */
class hk_image
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport hk_image();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~hk_image();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object hk_image that will be copied.
     */
    eProsima_user_DllExport hk_image(
            const hk_image& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object hk_image that will be copied.
     */
    eProsima_user_DllExport hk_image(
            hk_image&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object hk_image that will be copied.
     */
    eProsima_user_DllExport hk_image& operator =(
            const hk_image& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object hk_image that will be copied.
     */
    eProsima_user_DllExport hk_image& operator =(
            hk_image&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x hk_image object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const hk_image& x) const;

    /*!
     * @brief Comparison operator.
     * @param x hk_image object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const hk_image& x) const;

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint16_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint16_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint16_t& width();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint16_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint16_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint16_t& height();


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp();


    /*!
     * @brief This function copies the value in member image_data
     * @param _image_data New value to be copied in member image_data
     */
    eProsima_user_DllExport void image_data(
            const std::array<uint8_t, 3*1280*1024>& _image_data);

    /*!
     * @brief This function moves the value in member image_data
     * @param _image_data New value to be moved in member image_data
     */
    eProsima_user_DllExport void image_data(
            std::array<uint8_t, 3*1280*1024>&& _image_data);

    /*!
     * @brief This function returns a constant reference to member image_data
     * @return Constant reference to member image_data
     */
    eProsima_user_DllExport const std::array<uint8_t, 3*1280*1024>& image_data() const;

    /*!
     * @brief This function returns a reference to member image_data
     * @return Reference to member image_data
     */
    eProsima_user_DllExport std::array<uint8_t, 3*1280*1024>& image_data();

private:

    uint32_t m_index{0};
    std::string m_message;
    uint16_t m_width{0};
    uint16_t m_height{0};
    uint64_t m_timestamp{0};
    std::array<uint8_t, 3*1280*1024> m_image_data{0};

};

#endif // _FAST_DDS_GENERATED_HK_IMAGE_H_



